### ISSUE TITLE
I don't know the correct steps to OCR my pecha images.

### ISSUE THREAD

**Issue by chiehan1** [thubtenrigzin/docker-namsel-ocr#1]
I created ~/data and ~/data/out. And put my tibetan pecha images in the ~/data/out.
After that, I tried these command.

`docker run -itd --name namsel -v ~/data:/home/namsel-ocr/data thubtenrigzin/docker-namsel-ocr:latest bash`

`docker exec namsel ./pecha`

But my ocr_output.txt only contained a string of 'OCR text' on the first line.
Could someone help me to figure out what's wrong with my steps?
Thank you!

**Comment by thubtenrigzin** [comment]
Hello,
You don't need to create the /out directory, just ~/data and put your pecha scan images only in the ~/data directory to let it works.
Other thing, all you images have to be in .tif format.

Nota: /out directory will be used only by scantailor after the preprocess

**Comment by chiehan1** [comment]
Thank you so much!
I can OCR my images now.

But there are some problems,
This is my [image](https://drive.google.com/open?id=1ZLay47CZbLEiU2ujLHyyCddPHMCRnTdr)

I use this command
`docker exec namsel ./book`
<img width="837" alt="2018-07-17 12 24 24" src="https://user-images.githubusercontent.com/13195099/42796387-6b50986c-89bc-11e8-84e8-8b26cb543e16.png">

Is there anything I can improve? (e.g. scan quality)

**Comment by thubtenrigzin** [comment]
Please try these options:
- improve the quality of your source scan image by cleaning the "pixel dust"
- scan your book using high DPI like 600
- preprocess your scan images by choosing a threshold value between -40 to 40 (docker exec namsel ./preprocess [threshold value])

**Comment by chiehan1** [comment]
Thank you for the suggestion about scan and the setting of threshold value!
I have tried the threshold value to -40 or -55, it is better.
I will also re-scan my image to get better OCR results.
Thanks a lot!

**Comment by thubtenrigzin** [comment]
Please note that the threshold range value is from **-40** to **40** not -55
I hope everything is clear now and I think I can close this conversation on that issue now...
All the best to you!
